# Generated by Django 5.2.1 on 2025-06-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_moderatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
