# Generated by Django 5.2.1 on 2025-06-12 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('message', models.TextField()),
                ('how_did_you_hear', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='When the demo/interpretation is scheduled', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Expected duration of the session in minutes', null=True)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When the interpreter was assigned', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the booking was marked as completed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators', null=True)),
                ('required_language', models.CharField(blank=True, help_text='Language required for interpretation', max_length=100, null=True)),
                ('assigned_interpreter', models.ForeignKey(blank=True, help_text='The interpreter assigned to handle this booking', limit_choices_to={'is_interpreter': True, 'translatorprofile__is_approved': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Booking',
                'verbose_name_plural': 'Demo Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
