# Generated by Django 5.2.1 on 2025-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bookdemo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdemo',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', help_text='Current status of the booking', max_length=20),
        ),
    ]
