# Generated by Django 5.2.1 on 2025-06-12 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bookdemo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdemo',
            name='assigned_interpreter',
            field=models.ForeignKey(blank=True, help_text='The interpreter assigned to handle this booking', limit_choices_to={'is_interpreter': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
